almadekiltro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from re import template
from django.urls import path
from .views import listar_rechazadas, ver_rechazada,ver_aprobada,listar_aprobadas,rechazar_solicitud,aceptar_solicitud, ver_solicitud,eliminar_solicitudes,listar_solicitudes,eliminar_mascota_desaparecida,listar_mascotas_desaparecidas,home, contacto, agregar_mascota, listar_mascotas, modificar_mascota, eliminar_mascota, nosotros, registro, agregar_mascota_desaparecida, mascotasDesaparecidas, formulario_adopcion, ListaMascotasListView, ListMascotasPdf
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', home, name="home"),
    path('contacto/', contacto, name="contacto"),
    path('agregar-mascota/', agregar_mascota, name="agregar_mascota"),
    path('listar-mascotas/', listar_mascotas, name="listar_mascotas"),
    path('modificar-mascota/<id>/', modificar_mascota, name="modificar_mascota"),
    path('eliminar-mascota/<id>/', eliminar_mascota, name="eliminar_mascota"),
    path('registro/', registro, name="registro"),
    path('quienes-somos/', nosotros, name="nosotros"),
    path('accounts/login/', auth_views.LoginView.as_view(template_name="registration/login.html")),
    path('agregar_mascota_desaparecida/', agregar_mascota_desaparecida, name="agregar_mascota_desaparecida"),
    path('listar_mascota_desaparecida/', listar_mascotas_desaparecidas, name="listar_mascotas_desaparecidas"),
    path('eliminar_desaparecida/<id>/', eliminar_mascota_desaparecida, name="eliminar_mascota_desaparecida"),
    path('mascotas_desaparecidas/', mascotasDesaparecidas, name="mascotas_desaparecidas"),
    path('solicitud_adopcion/', formulario_adopcion, name="solicitud_adopcion"),
    path('listado_solicitudes/', listar_solicitudes, name="listar_solicitudes"),
    path('listado_aprobadas/', listar_aprobadas, name="listar_aprobadas"),
    path('listado_rechazadas/', listar_rechazadas, name="listar_rechazadas"),
    path('eliminar_solicitud/<id>/', eliminar_solicitudes, name="eliminar_solicitud"),
    path('ver_rechazada/<id>/', ver_rechazada, name="ver_rechazada"),
    path('ver_solicitud/<id>/', ver_solicitud, name="ver_solicitud"),
    path('ver_aprobada/<id>/', ver_aprobada, name="ver_aprobada"),
    path('aceptar_solicitud/<id>/', aceptar_solicitud, name="aceptar_solicitud"),
    path('rechazar_solicitud/<id>/', rechazar_solicitud, name="rechazar_solicitud"),
    path('lista_mascota/', ListaMascotasListView.as_view(),name="lista_mascota"),
    path('list_mascota_pdf/', ListMascotasPdf.as_view(),name="mascotas_all"),

    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="registration/recuperar_contraseña.html"
    ), name="reset_password"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name="registration/recuperar_mensaje.html"
    ), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="registration/recuperar_form.html"
    ), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name="registration/recuperar_done.html"
    ), name="password_reset_complete"),
    
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name = "registration/cambiar_pw.html"
    ), name="password_change"),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name = "registration/cambiar_pw_done.html"
    ), name="password_change"),

]

app/models.py
from django.db import models

class Raza(models.Model):
    nombre_raza = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre_raza


class Especie(models.Model):
    nombre_especie = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre_especie

# Opciones sexo de la mascota
opciones_sexo = [
    [0, "Hembra"],
    [1, "Macho"]
]

# Opciones tamaño de la mascota
opciones_tamaño = [
    [0, "Pequeño"],
    [1, "Mediano"],
    [2, "Grande"]
]

class Mascota(models.Model):
    nombre_mascota = models.CharField(max_length=250)
    imagen = models.ImageField(upload_to="mascota", null=True)
    edad_mascota = models.CharField(max_length=250)
    sexo = models.IntegerField(choices=opciones_sexo)
    descripcion = models.TextField()
    tamaño = models.IntegerField(choices=opciones_tamaño)
    peso = models.CharField(max_length=250)
    especie = models.ForeignKey(Especie, on_delete=models.PROTECT)
    raza = models.ForeignKey(Raza, on_delete=models.PROTECT)
   

    def __str__(self):
        return self.nombre_mascota

# Opciones tipo publicacion
opciones_publicacion = [
    ['Mascota Perdida', "Mascota Perdida"],
    ['Mascota Encontrada', "Mascota Encontrada"]
]
class MascotaDesaparecida(models.Model):
    nombre_desaparecida = models.CharField(max_length=250)
    imagen = models.ImageField(upload_to="mascotas_desaparecidas", null = True)
    fecha_desaparecida = models.DateField()
    fecha_publicacion = models.DateField(auto_now=True)
    region = models.CharField(max_length=250)
    comuna = models.CharField(max_length=250)
    lugar = models.CharField(max_length=250)
    numero_contacto = models.IntegerField(blank=True, null=True)
    descripcion = models.TextField()
    tipo_publicacion = models.CharField(max_length=50,choices=opciones_publicacion)

    def __str__(self):
        return self.nombre_desaparecida

# Opciones tipo vivienda
opciones_tipo_vivienda = [
    ['Casa', "Casa"],
    ['Departamento', "Departamento"]
]
# Opciones tipo vivienda
opciones_cantidad_mascotas = [
    [0, "0"],
    [1, "1"],
    [2, "2"],
    [3, "3"],
    [4, "4"],
    [5, "5"],
    [6, "6"]
]
opciones_estado_solicitud=[
    ['Pendiente', "Pendiente"],
    ['Aprobada', "Aprobada"],
    ['Rechazada', "Rechazada"],
]

class FormularioAdopcion(models.Model):
    nombres = models.CharField(max_length=250)
    apellidos = models.CharField(max_length=250)
    edad = models.IntegerField()
    telefono = models.IntegerField()
    tipo_vivienda = models.CharField(max_length=50,choices=opciones_tipo_vivienda)
    direccion = models.CharField(max_length=250)
    otra_mascota = models.BooleanField()
    fecha_solicitud = models.DateField(auto_now=True)
    cantidad_mascotas = models.IntegerField(choices=opciones_cantidad_mascotas)
    mascota = models.ForeignKey(Mascota, on_delete=models.PROTECT)  
    estado_solicitud = models.CharField(max_length=50, choices=opciones_estado_solicitud, default='Pendiente')

    def __str__(self):
        return self.nombres

class Fundacion(models.Model):
    nombre_fundacion = models.CharField(max_length=250)
    direccion_fundacion = models.CharField(max_length=250)
    contacto_fundacion = models.CharField(max_length=250)

    def __str__(self):
        return self.nombre_fundacion

# CONTACTO
opciones_consulta = [
    ['Consulta', "Consulta"],
    ['Reclamo', "Reclamo"],
    ['Sugerencia', "Sugerencia"],
    ['Agradecimientos', "Agradecimientos"]
]

class Contacto(models.Model):
    nombre =  models.CharField(max_length=250)
    correo = models.EmailField()
    tipo_consulta = models.CharField(max_length=20, choices=opciones_consulta)
    mensaje = models.TextField()

    def __str__(self):
        return self.nombre

app/templates/app/base.html
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../../static/app/css/navbar.css">
    <link rel="stylesheet" href="../../static/app/css/style.css">
    

    <title>Inicio</title>


    <!-- cargar css en django-->
    {% load static %} 

    {% block css %}
    {% endblock %}

</head>

<body>
    <!-- Navbar -->
    <div class="navbar navbar-expand-lg navbar-mainbg">
        <!-- Cambie de color y aparezca como titulo del navbar -->
        <div class="container">
            <img src="{% static 'app/img/logo_almadekiltro.png' %}" alt=""class="img-fluid mt-2 mb-2" style="width:12%;">
            <button class="navbar-toggler" type="button" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="auto" fill="currentColor" class="bi bi-list text-white" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                  </svg>
            </button>
            <div class="navbar-collapse collapse justify-content-end">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Inicio</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'nosotros' %}">¿Quienes Somos?</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mascotas Perdidas</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
                            <a class="dropdown-item" href="{% url 'mascotas_desaparecidas' %}">Ver Mascotas</a>
                            {% if perms.app.view_formularioadopcion %}
                            <a class="dropdown-item" href="{% url 'listar_mascotas_desaparecidas' %}">Listar Desaparecidas</a>
                            {% endif %}
                        </div>
                    </li>
                    {% if perms.app.add_mascota %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Mascotas Fundación</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
                            <a class="dropdown-item" href="{% url 'agregar_mascota' %}">Agregar mascotas</a>
                            <a class="dropdown-item border-bottom" href="{% url 'listar_mascotas' %}">Listar mascotas</a>
                            <a class="dropdown-item" href="{% url 'listar_solicitudes' %}">Solicitudes Pendientes</a>
                            <a class="dropdown-item" href="{% url 'listar_aprobadas' %}">Solicitudes Aprobadas</a>
                            <a class="dropdown-item" href="{% url 'listar_rechazadas' %}">Solicitudes Rechazadas</a>
                        </div>
                    </li>
                    {% endif %}
                     <!-- Si está autenticado -->
                     {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="text-transform: capitalize;">Bienvenido {{ user.first_name }}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
                            <a class="dropdown-item" href="{% url 'password_change' %}">Cambiar Contraseña</a>
                            <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                        </div>
                    </li>
                    <!-- Si no está autenticado -->
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Iniciar sesión</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
<br>
    <!-- Contenido de la web -->
    <div class="container">

        {% block contenido %} {% endblock %}

    </div>
    <br><br>

    <!-- Footer -->
    <br><br><br>
    <footer class="mt-5">
        <div class="container">
            <div class="row text-center py-3" id="content-footer">
                <div class="col-md-6">
                    <p class="letraFooter" id="letraFooter">¿Tienes alguna duda o reclamo?<a href="{% url 'contacto' %}">Contactanos</a></p>
                </div>
                <div class="col-md-6">
                    <p class="letraFooter"id="letraFooter">AlmadeKiltro &copy 2022</p>
                </div>
            </div>
        </div>
    </footer>

    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %} {% for m in messages %}
    <script>
        Swal.fire({
            "title": "Completado",
            "text": "{{m}}",
            "icon": "success"
        })
    </script>
    {% endfor %} {% endif %} 
    
    {% block js %} 
    
    
    {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="../../static/app/js/navbar.js"></script>
    
</body>

</html>

app/templates/app/contacto.html
{% extends 'app/base.html' %}

<!-- CARGA ARCHIVOS ESTATICOS -->
{% load static %}

<!-- BLOCK CSS -->
{% block css %}
<!-- Bootstrap CSS -->
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'app/css/mascotas.css' %}">  -->
<link rel="stylesheet" href="{% static 'app/css/login.css' %}">
{% endblock %}

<!-- BLOCK CONTENIDO -->
{% block contenido %}
<!-- Importamos crispy -->
{% load crispy_forms_tags %}
<!-- Contenido de la web -->
<h2 class="text-center letraInicio">Contactanos</h2>
<hr>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">
        <div class="card" id="cardAgregar">
            <div class="card-body">
                <form action="" class="formulario_contacto" method="POST">
                    <!-- Para ingresar datos-->
                    {% csrf_token %}
                    <!-- Fromulario Django-->
                    {{ form | crispy }}

                    <br>
                    <div class="d-flex justify-content-end">
                        <input type="reset" value="Cancelar" class="btn btn-secondary"> &nbsp;
                        <button type="submit" id="btnEnviar" class="btn btn-primary">Enviar</button>
                    </div>
                </form>

                {{mensaje}}
            </div>
        </div>
    </div>
</div>

{% endblock %}

app/templates/app/contacto_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Email Html</title>
</head>
<body>
    <!-- <h1 style="background-color: green;">{{content}}</h1>
    <h2 style="background-color: blue;">{{nombre}}</h2>
    <h2 style="background-color: rgb(255, 0, 0);">{{asunto}}</h2> -->
<div class="row">
    <div class="col-8 offset-md-2 mt-5">
        <div class="card" style="background-color: rgba(245, 245, 245, 0.4); width: 40%;">
            <div class="card-body" style="padding-left: 2%; padding-right: 2%;">
                <h1 style="text-align: center;">{{asunto}}</h1>
                <hr>
                <p>{{content}}</p>
                <h5 style="margin-top: 10px ;">Mensaje enviado por:</h5>
                <h5 style="text-transform: capitalize;">{{nombre}}</h5>
            </div>
        </div>
    
    </div>
</div>



    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/email_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Email Html</title>
</head>
<body>
    <!-- <h1 style="background-color: green;">{{content}}</h1>
    <h2 style="background-color: blue;">{{nombre}}</h2>
    <h2 style="background-color: rgb(255, 0, 0);">{{asunto}}</h2> -->
<div class="row">
    <div class="col-8 offset-md-2 mt-5">
        <div class="card" style="background-color: rgba(245, 245, 245, 0.4); width: 40%;">
            <div class="card-body" style="padding-left: 2%; padding-right: 2%;">
                <h1 style="text-align: center;">{{asunto}}</h1>
                <hr>
                <p>{{content}}</p>
                <h5 style="margin-top: 10px ;">Mensaje enviado por:</h5>
                <h5 style="text-transform: capitalize;">{{nombre}}</h5>
            </div>
        </div>
    
    </div>
</div>



    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

app/templates/app/home.html
{% extends 'app/base.html' %}

<!-- CARGA ARCHIVOS ESTATICOS -->
{% load static %}

<!-- BLOCK JS -->
{%block js %} {% endblock%}

<!-- BLOCK CSS -->
{% block css %}
<link rel="stylesheet" href="{% static 'app/css/mascotas.css' %}"> 

{% endblock %}

<!-- BLOCK CONTENIDO -->
{% block contenido %}
<!-- Contenido de la web -->
<div class="container mb-5 mt-5">
    <img src="{% static 'app/img/Banner_Home.png' %}" class="img_fluid imgBanner">
</div>
<div class="container ">
    <div class="row">
        <div class="col-12 search borderContainer pt-2">
            <form method="POST" class="row justify-content-between">
                {% csrf_token %}
                <div class="col-lg-4 mb-2">
                    <select class="form-select" aria-label="Default select example" name="buscar">
                        <option value="-1"selected>Todas las mascotas</option>
                        <option value="1">Perros</option>
                        <option value="2">Gatos</option>
                    </select>
                </div>
                <div class="col-lg-4 mb-2">
                    <select class="form-select" aria-label="Default select example" name="buscar2">
                        <option value="-1"selected>Elige el sexo</option>
                        <option value="0">Hembra</option>
                        <option value="1">Macho</option>
                    </select>
                </div>
                <div class="col-lg-4 d-flex justify-content-end mb-2">
                    <button type="submit" class="btn btnSolicitar text-white" value="search">Aplicar Filtros</button>
                </div>
            </form>
        </div>
    </div>
    <div class="row mt-5">{% for m in mascotas %}
        <div class="col-lg-3 col-md-4 col-xs-4 offset-xs-4 ">
            <div class="card sombra text-center mb-5">
                {% if m.imagen %}
                <img src="{{ m.imagen.url }}" class="img-fluid mascota mx-auto" alt="..."> 
                {% endif %}
                <div class="card-body cardMascota">
                    <div class="marginCard">   
                        <h3>{{ m.nombre_mascota}}</h3>
                        <hr>
                        <p>{{ m.descripcion }}</p>
                    </div>
                                  
                </div>
                <div class="pt-3 pb-2 mb-3">
                    <a href="{% url 'solicitud_adopcion'%}" class="btn btn-outline linkSolicitar text-center mt-2">Solicitar Adopción</a>
                </div> 
            </div>
        </div>
        {% empty %}
        <div class="row">
            <div class="col-12 text-center">
                <h1>¡Oh no! Lo sentimos no tenemos esas mascotas</h1>
                <img src="" alt="" class="img-fluid mx-auto">
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/app/nosotros.html
{% extends 'app/base.html' %}
<!-- CARGA ARCHIVOS ESTATICOS -->
{% load static %} {% block contenido %}

<style>
    .card-title {
        margin-left: 37%;
        font-style: italic
    }

    .card-img-top {
        height: 250px;
        width: 250px;
        margin-left: 20%;
    }

    .card-img-bot {
        display: block;
        height: 450px;
        width: 750px;
        margin-left: auto;
        margin-right: auto;
    }

    .card {
        background-color: #F5F5F5;
        border: none;
    }

    hr.one {
        height: 10px;
        border: none;
        border-radius: 10px;
        background: linear-gradient(to left, blue, red);
    }
</style>
<br>
<div class="card-group">
    <div class="card">
        <h5 class="card-title">Rescate</h5>
        <img class="card-img-top" src="{% static 'app/img/nosotros/1.jpeg' %}" alt="Card image cap">
    </div>
    <div class="card">
        <h5 class="card-title">Rehabilitación</h5>
        <img class="card-img-top" src="{% static 'app/img/nosotros/2.jpeg' %}" alt="Card image cap">
    </div>
    <div class="card">
        <h5 class="card-title">Reubicación</h5>
        <img class="card-img-top" src="{% static 'app/img/nosotros/3.jpeg' %}" alt="Card image cap">
    </div>
</div>
<br>
<div class="card-group">
    <div class="card">
        <h5 class="card-title">Alimentación</h5>
        <img class="card-img-top" src="{% static 'app/img/nosotros/4.jpeg' %}" alt="Card image cap">
    </div>
    <div class="card">
        <h5 class="card-title">Concientización</h5>
        <img class="card-img-top" src="{% static 'app/img/nosotros/5.jpeg' %}" alt="Card image cap">
    </div>
    <div class="card">
        <h5 class="card-title">Recolección</h5>
        <img class="card-img-top" src="{% static 'app/img/nosotros/6.jpeg' %}" alt="Card image cap">
    </div>
</div>
<br>
<hr class="one">
<br>
<div class="descripcion">
    <p style="font-size:18px;">Somos una fundación que cuenta con un pequeño refugio para rescatar animales en situación de calle. <br><br> Cuando logramos rescatar a estos animalitos, nos encargamos de rehabilitarlos y curarlos. Para lograrlo necesitamos siempre de la ayuda de
        nuestros voluntarios que salen a las calles a recolectar dinero.<br><br>Una vez estos animalitos están sanos, procedemos a buscarles un hogar y nos aseguramos de que los dueños cumplan con la tenencia responsable. <br><br> Por otro lado, nos encargamos
        de hacer recorridos diarios para alimentar a los animalitos que no podemos llevar al refugio. También aprovechamos de educar a las personas que nos siguen por redes sociales a través de infografías. <br><br> Esta fundación no habría surgido sin
        la ayuda de nuestros voluntarios y todas las personas que amablemente nos donan comida o dinero para nuestros angelitos. Si quieres ser parte de esta familia puedes comunicarte a través del siguiente correo: <b style="color: orange;">dekiltroalma@gmail.com</b>        <br><br>
    </p>
</div>
<hr class="one">

<div class="card">
    <img class="card-img-bot" src="{% static 'app/img/nosotros/8.jpg' %}">
    <br>
    <div class="text-center">
        <h5><i>Si deseas aportar para la alimentación de nuestras mascotas, realiza tu depósito a nuestra</i> <b style="color: orange;">Cta rut 15.353.203-6</b></h5>
    </div>
</div>
{% endblock %}